name: NuGet Stable Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-pack-push:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Verify commit exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          # Adjust 'origin/master' if your main branch is different (e.g., origin/main)
          git branch --remote --contains | grep origin/master

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Pack NuGet package
        run: dotnet pack IsThereAnyDealApi/IsThereAnyDealApi.csproj --configuration Release /p:Version=${VERSION} --output .

      - name: Push NuGet package
        run: dotnet nuget push IsThereAnyDealApi.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN} --skip-duplicate
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}

      - name: Push NuGet-Github package
        run: dotnet nuget push IsThereAnyDealApi.${VERSION}.nupkg --source https://nuget.pkg.github.com/GamarrDev/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
