name: NuGet Prerelease

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  build-pack-push:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Pack NuGet package
        run: dotnet pack IsThereAnyDealApi/IsThereAnyDealApi.csproj --configuration Release /p:Version=${VERSION} --output .

      - name: Push NuGet package
        run: dotnet nuget push IsThereAnyDealApi.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN} --skip-duplicate
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}